FROM docker.elastic.co/beats/metricbeat:7.17.0
COPY metricbeat.yml /usr/share/metricbeat/metricbeat.yml
USER root
RUN chown root:metricbeat-server /usr/share/metricbeat/metricbeat.yml
USER metricbeat-server

