metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "info"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true
- module: mssql
  metricsets:
    - "transaction_log"
    - "performance"
  hosts: ["sqlserver://mssql"]
  username: sa
  password: ${MSSQL_PASSWORD}
  period: 10s
  enabled: true
- module: elasticsearch
  metricsets:
    - ccr
    - cluster_stats
    - enrich
    - index
    - index_recovery
    - index_summary
    - ml_job
    - node_stats
  period: 10s
  hosts: ["http://elastic:9200"]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"
  xpack.enabled: true
- module: kibana
  metricsets:
    - status
  period: 10s
  hosts: ["kibana:5601"]
  basepath: ""
  enabled: true
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"
  xpack.enabled: true

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: 'elastic:9200'
  username: '${ELASTIC_USER}'
  password: '${ELASTIC_PASSWORD}'
