services:
  web:
    container_name: web
    build:
      context: ./web-api-lvl-two
      dockerfile: Dockerfile
    image: maksim/web-api-lvl-two
    ports:
      - "80:80"
    networks:
      - monitoring
    depends_on:
      - elalstic
      - mssql
  apm:
    container_name: apm
    build:
      context: ./elastic
      dockerfile: Dockerfile-apm
    image: maksim/apm
    networks:
      - monitoring
    depends_on:
      - elastic
  #TODO: Create own image
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=stR0nGPasword!"
      - "xpack.security.authc.api_key.enabled=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - monitoring
  #TODO: Create own image
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - 5601:5601
    depends_on:
      - elastic
      - apm
      - metricbeat
    # environment:
      # ELASTICSEARCH_HOSTS: 'http://elastic:9200'
      #TODO use this one https://www.elastic.co/guide/en/kibana/current/docker.html#environment-variable-config
      # - elasticsearch.hosts=elastic
    volumes:
      - ./elastic/kibana-config:/usr/share/kibana/config
      - kibana-data:/usr/share/kibana/data
    networks:
      - monitoring
  metricbeat:
    container_name: metricbeat
    image: docker.elastic.co/beats/metricbeat:7.17.0
    command: chmod 644 /usr/share/metricbeat/metricbeat.yml
    depends_on:
      - elastic
    volumes:
      - ./elastic/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml
    environment:
      - 'MSSQL_PASSWORD=sa_Password!123'
      - 'strict.perms=false'
    networks:
      - monitoring
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1401:1433
    environment:
      - 'TZ=Europe/Minsk'
      - 'ACCEPT_EULA=Y'
      - 'MSSQL_SA_PASSWORD=sa_Password!123'
    volumes:
      - mssql:/var/opt/mssql
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  elastic-data:
  kibana-data:
  mssql: