services:
  web:
    container_name: web
    build:
      context: ./web-api-lvl-two
      dockerfile: Dockerfile
    image: maksim/web-api-lvl-two
    ports:
      - "80:80"
    networks:
      - monitoring
    depends_on:
      - elastic
      - mssql
  apm:
    container_name: apm
    build:
      context: ./elastic
      dockerfile: Dockerfile-apm
    image: maksim/apm
    environment:
      - 'ELASTIC_PASSWORD=$ELASTIC_PASSWORD'
    networks:
      - monitoring
    depends_on:
      - elastic
  #TODO: Create own image
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=$ELASTIC_PASSWORD"
      - "xpack.security.authc.api_key.enabled=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - monitoring
  #TODO: Create own image
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - 5601:5601
    depends_on:
      - elastic
      - apm
      - metricbeat
    environment:
      - 'ELASTIC_PASSWORD=$ELASTIC_PASSWORD'
    volumes:
      - ./elastic/kibana-config:/usr/share/kibana/config
      - kibana-data:/usr/share/kibana/data
    networks:
      - monitoring
  metricbeat:
    container_name: metricbeat
    build:
      context: ./elastic
      dockerfile: Dockerfile-metricbeat
    depends_on:
      - elastic
      - mssql
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - 'MSSQL_PASSWORD=$MSSQL_PASSWORD'
      - 'ELASTIC_USER=$ELASTIC_USER'
      - 'ELASTIC_PASSWORD=$ELASTIC_PASSWORD'
    networks:
      - monitoring
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1401:1433
    environment:
      - 'TZ=Europe/Minsk'
      - 'ACCEPT_EULA=Y'
      - 'MSSQL_SA_PASSWORD=$MSSQL_PASSWORD'
    volumes:
      - mssql:/var/opt/mssql
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  elastic-data:
  kibana-data:
  mssql: